services:
  whatsapp-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bridge
    restart: unless-stopped
    volumes:
      - ./store:/app/store
      - /var/www/wa_code/image:/app/qr
    ports:
      - "8081:8080"
    environment:
      - TZ=UTC
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
    env_file:
      - .env