services:
  whatsapp-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bridge
    restart: unless-stopped
    volumes:
      - ./store:/app/store
    ports:
      - "8081:8080"
    environment:
      - TZ=UTC